### ISSUE TITLE
mkdir: cannot create directory ‘/mnt/kafka/1’: Permission denied

### ISSUE THREAD

**Issue by KawhiWei** [stefanjay/kafka-kraft-on-k8s#23]
I encountered a problem during deployment using the kafka kraft on k8s you provided, which prompted me to create a folder without permission within the container. What should I do to resolve this issue?

![image](https://github.com/stefanjay/kafka-kraft-on-k8s/assets/46982191/46e1f6b3-8aea-459c-98e5-da48a56b43c9)

**Comment by stefanjay** [comment]
Is this issue still valid? I`ll create a new release today which lets kafka run as root until this issue is fixed.

**Comment by KawhiWei** [comment]
> 这个问题仍然有效吗？我今天将创建一个新版本，让 kafka 以 root 身份运行，直到此问题得到解决。

Yes, the question remains valid

**Comment by stefanjay** [comment]
I looked into your issue and will publish a fix to resolve the issue.

```
kafka@kafka-0:/$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kafka          1  9.4  2.2 4761412 365264 ?      Ssl  20:03   0:03 /usr/local/openjdk-17/bin/java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGC
kafka        793  0.0  0.0   5992  3724 pts/0    Ss   20:04   0:00 bash
kafka        800  0.0  0.0   8592  3324 pts/0    R+   20:04   0:00 ps aux
kafka@kafka-0:/$ id
uid=1001(kafka) gid=1001(kafka) groups=1001(kafka)

**Comment by stefanjay** [comment]
fixed: https://github.com/stefanjay/kafka-kraft-on-k8s/pull/25
